{
 "title": "VerneMQ Node Metrics2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "SUMMARY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connected Clients",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vernemq_socket_open{}-vernemq_socket_close{}"
    }
   ]
  },
  {
   "title": "Queues Processes",
   "type": "stat",
   "description": "This is the current total of living queues (started queue processes). These queues might be in an online or an offline state (ie. belong to an online or offline client).",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vernemq_queue_processes" }
   ]
  },
  {
   "title": "Current MQTT Receive rate",
   "type": "stat",
   "description": "Current rate per second of received MQTT PUBLISH frames by the broker.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vernemq_mqtt_publish_received[30s]))"
    }
   ]
  },
  {
   "title": "Current MQTT send rate",
   "type": "stat",
   "description": "Current rate per second of sent MQTT PUBLISH frames by the broker.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vernemq_mqtt_publish_sent[30s]))"
    }
   ]
  },
  {
   "title": "VerneMQ Node Uptime",
   "type": "stat",
   "description": "VerneMQ Broker Uptime",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vernemq_system_wallclock" }
   ]
  },
  {
   "title": "Erlang VM Utilization",
   "type": "gauge",
   "description": "VerneMQ Broker average Erlang Scheduler utilization.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vernemq_system_utilization" }
   ]
  },
  {
   "title": "CLIENTS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connect/Disconnect Rate (per second)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      { "expr": "rate(vernemq_socket_open[30s])", "legendFormat": "Connect (Socket Open)" },
      {
       "expr": "rate(vernemq_socket_close[30s])",
       "legendFormat": "Disconnect (Socket Close)"
      }
     ]
    }
   ]
  },
  {
   "title": "QUEUES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Queue Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "vernemq_queue_processes", "legendFormat": "Queue Total" }
     ]
    },
    {
     "title": "Queue Setup and Teardown Rate (per second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      { "expr": "rate(vernemq_queue_setup[60s])", "legendFormat": "Queue Setup" },
      {
       "expr": "rate(vernemq_queue_teardown[60s])",
       "legendFormat": "Queue Teardown"
      }
     ]
    },
    {
     "title": "Messages in Queues",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(vernemq_queue_message_in[1m])",
       "legendFormat": "In"
      },
      {
       "expr": "rate(vernemq_queue_message_out[1m])",
       "legendFormat": "Out"
      },
      { "expr": "rate(queue_message_drop[1m])", "legendFormat": "Dropped" },
      {
       "expr": "rate(queue_message_unhandled[1m])",
       "legendFormat": "Unhandled"
      }
     ]
    }
   ]
  },
  {
   "title": "SUBSCRIPTIONS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Router Subscriptions Total",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "vernemq_router_subscriptions", "legendFormat": "Subscriptions Total" }
     ]
    },
    {
     "title": "Router Memory",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "vernemq_router_memory", "legendFormat": "Router Memory" }
     ]
    }
   ]
  },
  {
   "title": "ERLANG VM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Erlang Scheduler Utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "vernemq_system_utilization", "legendFormat": "System Utilization" }
     ]
    },
    {
     "title": "System Reductions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(vernemq_system_reductions[30s])",
       "legendFormat": "System Reductions"
      }
     ]
    },
    {
     "title": "Erlang Scheduler Utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "vernemq_system_utilization_scheduler_1",
       "legendFormat": "Scheduler 1"
      },
      {
       "expr": "vernemq_system_utilization_scheduler_2",
       "legendFormat": "Scheduler 2"
      },
      {
       "expr": "vernemq_system_utilization_scheduler_3",
       "legendFormat": "Scheduler 3"
      },
      {
       "expr": "vernemq_system_utilization_scheduler_4",
       "legendFormat": "Scheduler 4"
      }
     ]
    },
    {
     "title": "Erlang System Context Switches",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(vernemq_system_context_switches[30s])",
       "legendFormat": "Erlang Context Switches"
      }
     ]
    },
    {
     "title": "System IO",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(vernemq_system_io_in[30s])",
       "legendFormat": "System IO IN"
      },
      {
       "expr": "rate(vernemq_system_io_out[30s])",
       "legendFormat": "System IO OUT"
      }
     ]
    },
    {
     "title": "Erlang System Run Queue",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "vernemq_system_run_queue", "legendFormat": "Erlang Run Queue" }
     ]
    },
    {
     "title": "Erlang System Garbage Collection Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(vernemq_system_gc_count[30s])",
       "legendFormat": "Erlang GC Count"
      }
     ]
    },
    {
     "title": "Erlang System Number of Words Reclaimed by GC",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(vernemq_system_words_reclaimed_by_gc[30s])",
       "legendFormat": "Erlang GC Words Reclaimed"
      }
     ]
    }
   ]
  },
  {
   "title": "BYTES IN & OUT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Received",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(vernemq_bytes_received{}[30s])",
       "legendFormat": "Bytes Received"
      }
     ]
    },
    {
     "title": "Bytes Sent",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(vernemq_bytes_sent{}[30s])",
       "legendFormat": "Bytes Sent"
      }
     ]
    }
   ]
  },
  {
   "title": "RETAIN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Retain Memory use",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "vernemq_retain_memory", "legendFormat": "Retain Memory" }
     ]
    },
    {
     "title": "Retained Messages Total",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "vernemq_retain_messages", "legendFormat": "Retained Messages" }
     ]
    }
   ]
  },
  {
   "title": "TCP SOCKETS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP Sockets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      { "expr": "rate(vernemq_socket_open[30s])", "legendFormat": "Socket Open" },
      {
       "expr": "rate(vernemq_socket_close[30s])",
       "legendFormat": "Socket Close"
      },
      {
       "expr": "rate(vernemq_socket_error[30s])",
       "legendFormat": "Socket Error"
      }
     ]
    }
   ]
  },
  {
   "title": "NODE TO CLUSTER COMMUNICATION",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Communication",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(vernemq_cluster_bytes_sent[30s])",
       "legendFormat": "Cluster Bytes Sent"
      },
      {
       "expr": "rate(vernemq_cluster_bytes_received[30s])",
       "legendFormat": "Cluster Bytes Received"
      },
      {
       "expr": "rate(vernemq_cluster_bytes_dropped[30s])",
       "legendFormat": "Cluster Bytes Dropped"
      }
     ]
    }
   ]
  },
  {
   "title": "MQTT CONNECT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "MQTT CONNACK Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(vernemq_mqtt_connack_bad_credentials_sent[30s])",
       "legendFormat": "Connack Bad Credentials"
      },
      {
       "expr": "rate(vernemq_mqtt_connack_identifier_rejected_sent[30s])",
       "legendFormat": "Connack ID rejected"
      },
      {
       "expr": "rate(vernemq_mqtt_connack_not_authorized_sent[30s])",
       "legendFormat": "Connack Not Authorized"
      },
      {
       "expr": "rate(vernemq_mqtt_connack_server_unavailable_sent[30s])",
       "legendFormat": "Connack Server Unavailable"
      },
      {
       "expr": "rate(vernemq_mqtt_connack_unacceptable_protocol_sent[30s])",
       "legendFormat": "Connack Unacceptable Protocol"
      }
     ]
    },
    {
     "title": "MQTT CONNACK",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(vernemq_mqtt_connect_received[30s])",
       "legendFormat": "MQTT CONNECT Received"
      },
      {
       "expr": "rate(vernemq_mqtt_connack_accepted_sent[30s])",
       "legendFormat": "MQTT CONNACK sent"
      }
     ]
    }
   ]
  },
  {
   "title": "MQTT SUBSCRIBE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Subscribe & Subscribe Errors",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(vernemq_mqtt_subscribe_received[30s])",
       "legendFormat": "Subscribe Received"
      },
      {
       "expr": "rate(vernemq_mqtt_suback_sent[30s])",
       "legendFormat": "SUBACK sent"
      },
      {
       "expr": "rate(vernemq_mqtt_subscribe_error[30s])",
       "legendFormat": "Subscribe Error"
      },
      {
       "expr": "rate(vernemq_mqtt_subscribe_auth_error[30s])",
       "legendFormat": "Subscribe Auth Error"
      }
     ]
    },
    {
     "title": "Unsubscribe & Unsubscribe Errors",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(vernemq_mqtt_unsubscribe_received[30s])",
       "legendFormat": "Unsubscribe Received"
      },
      {
       "expr": "rate(vernemq_mqtt_unsuback_sent[30s])",
       "legendFormat": "UNSUBACK sent"
      },
      { "expr": "vernemq_mqtt_unsubscribe_error", "legendFormat": "Unsubscribe Error" }
     ]
    }
   ]
  },
  {
   "title": "MQTT PUBLISH",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "QOS 0,1,2: PUBLISH Received, Sent & Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(vernemq_mqtt_publish_received[30s])",
       "legendFormat": "PUBLISH Received"
      },
      {
       "expr": "rate(vernemq_mqtt_publish_sent[30s])",
       "legendFormat": "PUBLISH Sent"
      },
      {
       "expr": "rate(vernemq_mqtt_publish_error[30s])",
       "legendFormat": "PUBLISH Error"
      },
      {
       "expr": "vernemq_mqtt_publish_auth_error",
       "legendFormat": "PUBLISH Auth Error"
      }
     ]
    },
    {
     "title": "QOS 1: PUBACK Received, Sent & Invalid",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(mqtt_puback_received[30s])",
       "legendFormat": "PUBACK Received"
      },
      { "expr": "rate(mqtt_puback_sent[30s])", "legendFormat": "PUBACK Sent" },
      {
       "expr": "rate(mqtt_puback_invalid_error[30s])",
       "legendFormat": "PUBACK Invalid"
      }
     ]
    },
    {
     "title": "QOS 2: PUBREC Received, Sent & Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(mqtt_pubrec_received[30s])",
       "legendFormat": "PUBREC Received"
      },
      { "expr": "rate(mqtt_pubrec_sent[30s])", "legendFormat": "PUBREC Sent" },
      {
       "expr": "rate(mqtt_pubrec_invalid_error[30s])",
       "legendFormat": "PUBREC Invalid"
      }
     ]
    },
    {
     "title": "QOS 2: PUBREL Received & Sent",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "rate(mqtt_pubrel_received[30s])",
       "legendFormat": "PUBREL Received"
      },
      { "expr": "rate(mqtt_pubrel_sent[30s])", "legendFormat": "PUBREL Sent" }
     ]
    },
    {
     "title": "QOS 2: PUBCOMP Received, Sent & Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
     "targets": [
      {
       "expr": "rate(mqtt_pubcomp_received[30s])",
       "legendFormat": "PUBCOMP Received"
      },
      { "expr": "rate(mqtt_pubcomp_sent[30s])", "legendFormat": "PUBCOMP Sent" },
      {
       "expr": "rate(mqtt_pubcomp_invalid_error[30s])",
       "legendFormat": "PUBCOMP Invalid"
      }
     ]
    }
   ]
  },
  {
   "title": "MQTT PING",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "PINGREQ & PINGRESP",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(vernemq_mqtt_pingreq_received[30s])",
       "legendFormat": "PINGREQ Received"
      },
      {
       "expr": "rate(vernemq_mqtt_pingresp_sent[30s])",
       "legendFormat": "PINGRESP Sent"
      }
     ]
    }
   ]
  },
  {
   "title": "MISC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Expired Clients",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "vernemq_client_expired", "legendFormat": "Expired Clients" }
     ]
    },
    {
     "title": "Invalid Message Size Error",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(vernemq_mqtt_invalid_msg_size_error[30s])",
       "legendFormat": "Invalid Message Size Error"
      }
     ]
    }
   ]
  }
 ]
}