# datasources.yaml
apiVersion: 1
datasources:
  - name: prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
  - name: influxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: my-org
      defaultBucket:
    secureJsonData:
      token: mytoken